repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/mortimerliu/leetcode-readme
    rev: '2bdc93359710406fabca59f5fe83d176c238b8cd'
    hooks:
    -   id: leetcode-readme
    -   id: cleanup-files
        args: [-v]
